### ISSUE TITLE
appium-playwright-driver - Not found

### ISSUE THREAD

**Issue by billykrahl** [dlenroc/appium-playwright-driver#2]
npx appium@next driver install --source npm @dlenroc/appium-playwright-driver
✖ Installing '@dlenroc/appium-playwright-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock @dlenroc/appium-playwright-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": "E404",
    "summary": "Not Found - GET https://registry.npmjs.org/@dlenroc%2Fappium-playwright-driver - Not found",
    "detail": "\n '@dlenroc/appium-playwright-driver@*' is not in this registry.\n\nNote that you can also install from a\ntarball, folder, http url, or git url."        
  }

**Comment by dlenroc** [comment]
This project was created for fun and was never published on npm, so encountering this error is expected. I would not recommend using it for anything important.

If you'd like to experiment with it, you can follow these steps:

1. Clone the project:
   ```
   git clone git@github.com:dlenroc/appium-playwright-driver.git
   ```

2. Install its dependencies and build it:
   ```
   npm install
   ```

3. Install it into Appium:
   ```
   appium driver install --source local "$(pwd)"
   ```

4. Experiment, make adjustments to the code, or explore its functionality as you like.
