### ISSUE TITLE
How to experiment?

### ISSUE THREAD

**Issue by mstankovic** [dlenroc/appium-playwright-driver#3]
Hello @dlenroc 

I have found this project very interested! I would like to play with it but need answers on few question?
Playwright (standalone) has experimental support for Android devices but not for Ios. 

- What is the idea of the project?
- Can I install this driver on Appium v2.x?
- If able to install how to configure playwright to point on my Appium and set capabilities? 
- true or false? If I install appium-playwright-driver, run appium server, create Playwright project, configure capabilities through playwright -> I would be able to run playwright tests on mobile devices?

**Comment by dlenroc** [comment]
This project was created as a hobby/experiment, so I wouldn't recommend using it for actual work. However, you can clone it, explore it, and have fun experimenting with it.

<br>

> What is the idea of the project?

The idea was to receive WebDriver commands and translate them into Playwright equivalents to experiment with concurrent test execution using separate contexts and browsers, all without modifying existing tests—by simply replacing browsers from Selenium Grid with Playwright's. 


> Can I install this driver on Appium v2.x?

Appium 2.x supports custom driver and plugin installation; see the [README](https://github.com/dlenroc/appium-playwright-driver/tree/72332bc200d559556d7be339465312ed0d0f7bd7?tab=readme-ov-file#installation) for instructions.



> If able to install how to configure playwright to point on my Appium and set capabilities?

This isn't possible; Playwright cannot execute tests through the WebDriver protocol unless there is a project that translates DevTools Protocol commands sent by Playwright into W3C WebDriver equivalents or adds support to Playwright.



> true or false? If I install appium-playwright-driver, run appium server, create Playwright project, configure capabilities through playwright -> I would be able to run playwright tests on mobile devices?

**False** – This project implements only the essential WebDriver protocol features to run WebDriver-based tests. It does not support Playwright-specific or mobile commands, though you could implement those yourself if interested in that area.

**Comment by mstankovic** [comment]
Thank you!
